export type Province = {
  value: string;
  label: string;
  districts: string[];
};

export const MOZAMBIQUE_PROVINCES: Province[] = [
  {
    value: "niassa",
    label: "Niassa",
    districts: [
      "Cuamba",
      "Lichinga",
      "Majune",
      "Mandimba",
      "Marrupa",
      "Maúa",
      "Mavago",
      "Mecanhelas",
      "Mecula",
      "Metarica",
      "Muembe",
      "N'gauma",
      "Nipepe",
      "Sanga",
    ],
  },
  {
    value: "cabo-delgado",
    label: "Cabo Delgado",
    districts: [
      "Ancuabe",
      "Balama",
      "Chiúre",
      "Ibo",
      "Macomia",
      "Mecúfi",
      "Meluco",
      "Metuge",
      "Mocímboa da Praia",
      "Montepuez",
      "Mueda",
      "Muidumbe",
      "Namuno",
      "Nangade",
      "Palma",
      "Pemba",
      "Quissanga",
    ],
  },
  {
    value: "nampula",
    label: "Nampula",
    districts: [
      "Angoche",
      "Eráti",
      "Ilha de Moçambique",
      "Lalaua",
      "Larde",
      "Liúpo",
      "Malema",
      "Meconta",
      "Mecubúri",
      "Memba",
      "Mogincual",
      "Mogovolas",
      "Moma",
      "Monapo",
      "Mossuril",
      "Muecate",
      "Murrupula",
      "Nacala-a-Velha",
      "Nacala Porto",
      "Nacarôa",
      "Nampula",
      "Rapale",
      "Ribáuè",
    ],
  },
  {
    value: "zambezia",
    label: "Zambézia",
    districts: [
      "Alto Molócuè",
      "Chinde",
      "Derre",
      "Gilé",
      "Gurúè",
      "Ile",
      "Inhassunge",
      "Luabo",
      "Lugela",
      "Maganja da Costa",
      "Milange",
      "Mocuba",
      "Mocubela",
      "Molumbo",
      "Mopeia",
      "Morrumbala",
      "Mulevala",
      "Namacurra",
      "Namarroi",
      "Nicoadala",
      "Pebane",
      "Quelimane",
    ],
  },
  {
    value: "tete",
    label: "Tete",
    districts: [
      "Angónia",
      "Cahora-Bassa",
      "Changara",
      "Chifunde",
      "Chiúta",
      "Dôa",
      "Macanga",
      "Magoé",
      "Marara",
      "Marávia",
      "Moatize",
      "Mutarara",
      "Tete",
      "Tsangano",
      "Zumbo",
    ],
  },
  {
    value: "manica",
    label: "Manica",
    districts: [
      "Báruè",
      "Chimoio",
      "Gondola",
      "Guro",
      "Macate",
      "Machaze",
      "Macossa",
      "Manica",
      "Mossurize",
      "Sussundenga",
      "Tambara",
      "Vanduzi",
    ],
  },
  {
    value: "sofala",
    label: "Sofala",
    districts: [
      "Beira",
      "Búzi",
      "Caia",
      "Chemba",
      "Cheringoma",
      "Chibabava",
      "Dondo",
      "Gorongosa",
      "Machanga",
      "Maringué",
      "Marromeu",
      "Muanza",
      "Nhamatanda",
    ],
  },
  {
    value: "inhambane",
    label: "Inhambane",
    districts: [
      "Funhalouro",
      "Govuro",
      "Homoíne",
      "Inhambane",
      "Inharrime",
      "Inhassoro",
      "Jangamo",
      "Mabote",
      "Massinga",
      "Morrumbene",
      "Panda",
      "Vilankulo",
      "Zavala",
    ],
  },
  {
    value: "gaza",
    label: "Gaza",
    districts: [
      "Bilene",
      "Chibuto",
      "Chicualacuala",
      "Chigubo",
      "Chókwè",
      "Guijá",
      "Limpopo",
      "Mabalane",
      "Manjacaze",
      "Mapai",
      "Massangena",
      "Massingir",
      "Xai-Xai",
    ],
  },
  {
    value: "maputo-provincia",
    label: "Maputo Província",
    districts: [
      "Boane",
      "Magude",
      "Manhiça",
      "Marracuene",
      "Matola",
      "Matutuíne",
      "Moamba",
      "Namaacha",
    ],
  },
  {
    value: "maputo-cidade",
    label: "Maputo Cidade",
    districts: [
      "KaMpfumo",
      "Nlhamankulu",
      "KaMaxakeni",
      "KaMavota",
      "KaMubukwana",
      "KaTembe",
      "KaNyaka",
    ],
  },
];

export function getProvinceOptions() {
  return MOZAMBIQUE_PROVINCES.map((province) => ({
    value: province.value,
    label: province.label,
  }));
}

export function getDistrictsByProvince(provinceValue: string) {
  const province = MOZAMBIQUE_PROVINCES.find((p) => p.value === provinceValue);

  if (!province) return [];

  return province.districts.map((district) => ({
    value: district.toLowerCase().replace(/\s+/g, "-"),
    label: district,
  }));
}
